### ISSUE TITLE
Soundness bug with `--nan-check`

### ISSUE THREAD

**Issue by SaswatPadhi** [diffblue/cbmc#5507] opened 2020-09-25 19:48 UTC
CBMC version: 5.14.1
Operating system: Mac OS Catalina

CBMC fails to detect a NaN value in the following harness:

```c
#include <math.h>
#include <inttypes.h>
#include <stdio.h>

union to_nan {
    uint32_t i;
    float f;
};

void main() {
    union to_nan t = { UINT32_MAX };
    float g = t.f + 0.0;                // to trigger a floating-point NaN "operation"
    printf("%f %d", g, isnan(g));       // to test compiler behavior
#ifdef CBMC                             // ignore when just compiling with gcc
    assert(isnan(g));
#endif
}
```

Compiling the above program and executing it produces the following output:

```
$ gcc test.c && ./a.out
nan 1
```

**Exact command line resulting in the issue:**

We ran CBMC with `--nan-check` and enabled the assertion:
```
$ cbmc --nan-check -DCBMC test.c
```

**What behaviour did you expect:**

CBMC should have failed to verify the program and should have reported a NaN counterexample (the `t.f` value).

**What happened instead:**

CBMC reports that the assertion was satisfied (so `g` is indeed NaN) but does not raise an error with `--nan-check` and reports that verification was successful.

```
$ cbmc --nan-check -DCBMC test.c
CBMC version 5.14.1 (cbmc-5.14.1) 64-bit x86_64 macos
Parsing test.c
Converting
Type-checking test
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 85 steps
simple slicing removed 0 assignments
Generated 1 VCC(s), 0 remaining after simplification

** Results:
test.c function main
[main.assertion.1] line 15 assertion tmp_if_expr$2: SUCCESS

** 0 of 1 failed (1 iterations)
VERIFICATION SUCCESSFUL
```

**Comment by SaswatPadhi** [comment] 2020-09-25 19:48
cc: @danielsn

**Comment by martin-cs** [comment] 2020-09-27 16:50
Thanks @SaswatPadhi for a really good bug report.

I think there are a couple of things going on here.  One is what `--nan-check` actually does.  It is a check for /generating/ NaN : 
https://github.com/diffblue/cbmc/blob/develop/src/analyses/goto_check.cpp#L1051
as your value is a NaN before the addition, it doesn't generate a new one ... so you get this behaviour.  I can see there being an argument about whether this is the correct behaviour but I feel that it might be because it separates the generation and propagation.

Please can you double check the command-line on the example at the end?  I would expect there to be two assertions if `-DCBMC` is given.  That would seem like another problem.

**Comment by SaswatPadhi** [comment] 2020-09-28 23:35
Hi @martin-cs,

Thanks for the quick response. The point about generation vs propagation makes sense. But then, I would expect the assignment in line 11 to be flagged (CBMC could check that the assigned value can be `correctly` interpreted as each of the union types), or the access in line 12 to be flagged (CBMC could check that the accessed value from the union is a valid float). I am not sure what the scope of this check should be, probably requires a broader discussion ...

I just double checked the output, and I I see the same thing as I originally reported: a single assertion (which CBMC reports as valid). Without `-DCBMC`, there are none, and with `-DCBMC` there is only one at line 15.

**Comment by piotr-grabalski** [comment] 2020-09-30 07:35
Hi All, 

Sorry in advance if I got something wrong in here but as far as I understand the problem this is not necessarily an issue. The `--nan-check` flag is examining an arithmetic operation for generating a not-a-number value and none of the operations from the example is doing that. In the example, `float g = t.f + 0.0;`, is resulting in `NaN` but this is not because the operation generates a new `NaN` value, `NaN` value is a part of the operation so the result is kind of expected to be `NaN`, therefore no assertion is added.
The main problem here is that documentation of `--nan-check` is not fully describing the analysis performed when the flag is used. The result of the flag usage is that CBMC will examine if a floating point operation will generate a new `NaN` value (e.g. `float g = 0.0/0.0;`).
Arguably accessing the union member should generate an assertion but this I think is not qualifying as an arithmetic operation. We can extend the functionality of `--nan-check` flag to include casting as well but this should be treated rather as an feature. 

Please let me know if that makes sense.

Thanks,
Piotr

**Comment by martin-cs** [comment] 2020-09-30 12:47
@piotr-grabalski : yes, the check is for generation of `NaN` not propagation.  I think it is better that way because A. there is already a way of checking whether something is NaN, B. propagation will give a lot more false alarms and generally you want to find the source.

@SaswatPadhi : neither L11 or L12 is generating a `NaN` so I am not sure they should be flagged.  If you test for `NaN` on union field access then any NaN stored in these will generate alarms everywhere and you are back to the noise problem of tracking propagation rather than generation.

**Comment by SaswatPadhi** [comment] 2020-10-04 15:52
Thanks @piotr-grabalski, @martin-cs.

I see your point about generation vs propagation. Let me ping @danielsn -- he knows more of our codebase and where thde checks are used. We can close this issue if he agrees as well.

**Comment by piotr-grabalski** [comment] 2020-10-07 09:36
Hi @SaswatPadhi, @danielsn 

I have made a change which is now merged to develop that is extending --nan-check flag documentation and provides a test for it's behaviour (details: https://github.com/diffblue/cbmc/commit/152719fb8b0f93ea6c327401eaa5d15db0b0c2da).

Are you happy to close this issue?

Thanks,
Piotr

**Comment by hannes-steffenhagen-diffblue** [comment] 2020-11-10 11:01
Closing for now as it seems not a bug

**Closed as completed** 2020-11-10 11:00 UTC
Labels: aws
