### ISSUE TITLE
Implement tolower from string.h

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5378] opened 2020-06-10 17:55 UTC
CBMC version: 5.12 (cbmc-5.12-372-g70ca8a694)
Operating system: macOS Mojave Version 10.14.6
Exact command line resulting in the issue: N/A.
What behaviour did you expect: We should be able assert if the result of a `tolower` function is correct.
What happened instead: The assertion fails.

```c
int s2n_blob_char_to_lower(struct s2n_blob *b)
{
    PRECONDITION_POSIX(s2n_blob_is_valid(b));
    for (size_t i = 0; i < b->size; i++) {
        b->data[i] = tolower(b->data[i]);
    }
    POSTCONDITION_POSIX(s2n_blob_is_valid(b));
    return S2N_SUCCESS;
}

if(s2n_blob_char_to_lower(blob) == S2N_SUCCESS) {
    size_t index;
    __CPROVER_assume(index < blob->size);
    assert(blob->data[index] < 'A' || blob->data[index] > 'Z');
}
```
Extracted from https://github.com/awslabs/s2n/pull/1926

**Comment by hannes-steffenhagen-diffblue** [comment] 2020-07-10 08:42
`tolower` is implemented in CBMC, but it is from `ctype.h`, not `string.h`.

A small test case works like I would expect:

```
#include <ctype.h>
#include <string.h>

int main(void) {
  char *hello = strdup("HELLO");
  for(char *c = hello; *c; ++c) {
    *c = tolower(*c);
  }
  assert(strcmp(hello, "hello") == 0);
  assert(0 && "false assertion for reachability checks");
}
```

And `cbmc --unwind 10` (manual unwind limit necessary because constant folding fails here) yields, as expected:

```
test.c function main
[main.assertion.1] line 9 assertion return_value_strcmp == 0: SUCCESS
[main.assertion.2] line 10 assertion 0 != 0 && (__CPROVER_bool)"false assertion for reachability checks": FAILURE
```

Our models for `ctype.h` functions (including `tolower`) live [here](https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/library/ctype.c), and as far as I know we’ve had these for a while. If you had any problems relating to `tolower` occur during your work the root cause would be something else, would you mind updating this if you run into this again @feliperodri?

**EDIT** I think I see what might have happened here: Apparently `cbmc` fails to resolve `tolower` to its library function because it is not declared here (due to wrong include). This _apparently_ also causes `cbmc` to fail to look up the library function. This can be reproduced by removing the `#include <ctype.h>` line from the test above.

This is obviously _very_ unfortunate, such changes in output shouldn’t happen as silently as this (there is a warning but it’s in an easy to miss and ignore spot). I am not quite sure what the best way to address this is, but it might just be to treat warnings about implicitly defined functions as errors instead as that easily may have unintended consequences (and is nearly always an error in the original source too).

**Comment by hannes-steffenhagen-diffblue** [comment] 2020-07-13 14:23
We track the underlying issue (i.e. easy to miss/misinterpret diagnostics) as ADA-572

**Comment by hannes-steffenhagen-diffblue** [comment] 2020-07-15 13:36
Closing for now, as while the diagnostics aren’t as helpful as they should be, the requested functionality (i.e. implementation of `tolower`) is already there.

**Closed as completed by hannes-steffenhagen-diffblue** 2020-07-15 13:36 UTC
Labels: aws
