### ISSUE TITLE
release flow question

### ISSUE THREAD

**Issue by chenrui333** [diffblue/cbmc#5448] opened 2020-08-11 00:28 UTC
I saw the latest release `5.8` was released back on 2017 Aug 11. And all the recent `5.12.x` releases are tagged with `prerelease`.

So my question is do you folks plan to do a formal release any time soon?

Kind of related to https://github.com/Homebrew/homebrew-core/pull/59425

**Comment by martin-cs** [comment] 2020-08-11 10:55
The last "official" release was 5.11 on 2018-12-15.

http://www.cprover.org/cbmc/

I have no idea what the current policy is or who is in charge of it.  If @hannes-steffenhagen-diffblue says ( https://github.com/Homebrew/homebrew-core/pull/59425#issuecomment-671856239 ) there are going to be by-weekly releases then that's probably it.

**Comment by hannes-steffenhagen-diffblue** [comment] 2020-08-11 11:00
@martin-cs Yes, so the problem we have right now is that in practice we don't really have a formal release process. It wasn't really clear to us exactly which criteria should lead to a “formal” release, what _was_ clear was that releases weren’t happening frequently enough to be useful (in practice, anyone trying to benefit from recent bug fixes and such would have to build from source, which isn’t a great place to be in).

So for now the idea was to have biweekly tagged releases so we have at least something to point towards version wise. AFAIK this project doesn’t have anything like a roadmap we could use as guidance instead, and as far as arbitrary guidelines go we figured this was as good as any.

It would be nice if we had a better way to organise the cbmc community and work out such things in a more visible way, but I’m not sure what that would look like.

**Comment by martin-cs** [comment] 2020-08-11 11:35
@hannes-steffenhagen-diffblue completely agree. Right now I am not sure there are any formal processes other than those enforced by github.  Having regular releases would be good, likewise package / binary builds for various platforms.  A bi-weekly tag is certainly a step better than what we had.

As for road-map and community; definitely, would be great, happy to help.  There are many ways that it could be organised, slack channel, e-mail, etc. but, really until we have corum on the code owners ( @kroening @tautschnig @peterschrammel @smowton @chrisr-diffblue ) there is not much that can be done.  The problem is social, not technological.

**Comment by chenrui333** [comment] 2020-08-11 12:26
Sorry for the bad wording, when I say "formal" release, I really just mean, the semantic versioning and release notes (that would just manifest what has been done). 

Everyone wants to use the latest and greatest software with latest functional and security patches, but still, sometimes, it would bring little bit frustrations with keeping the software up to date. With that being said, the I do see the semantic value of the github tags (also you folks have already used it before).

Speaking of the release cadence, I think biweekly release cycle is totally fine, I think it is totally cool with us.

Let me know if my question or comment makes more sense now. :)

**Comment by smowton** [comment] 2020-08-11 20:06
I don't have a position on release cycles; I just try to keep reviewing to keep PRs from getting blocked up when other codeowners are busy.

**Comment by tautschnig** [comment] 2022-06-23 10:07
Resolving with the following comments:
- We now release every other week.
- The process steps are documented in doc/ADR/release_process.md

**Closed as completed by tautschnig** 2022-06-23 10:07 UTC
