### ISSUE TITLE
Spurious warnings from DFCC instrumentation

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7349] opened 2022-11-16 02:45 UTC
CBMC version: `5.69.1 (cbmc-5.59.0-676-gb4a4122dee)`
Operating system: N/A
Exact command line resulting in the issue:
First, clone my fork for [coreJSON](https://github.com/feliperodri/coreJSON/tree/JSON_validate-proof). Then, navigate to the proof located at `coreJSON/verification/cbmc/proofs/skipString/`. Finally, run the proof using `make veryclean; time make`.
What behaviour did you expect: No warnings.
What happened instead: I keep getting the following warnings, however, the following functions are unreachable from the entry point of this proof.

```
no body for function '__CPROVER_assignable'

no body for function '__CPROVER_assignable'

DFCC instrumentation: 'skipObjectScalars' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'JSON_Iterate' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'multiSearch' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'JSON_SearchConst' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipScalars' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'objectSearch' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipExponent' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipSpaceAndComma' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'nextValue' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'JSON_Validate' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipDigits' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'JSON_SearchT' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'iterate' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'arraySearch' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipAnyLiteral' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipNumber' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipAnyScalar' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipArrayScalars' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipCollection' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'nextKeyValuePair' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipSpace' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipLiteral' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'strnEq' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipDecimals' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'getType' body is not available. Results may be unsound if the actual function has side effects.

DFCC instrumentation: 'skipQueryPart' body is not available. Results may be unsound if the actual function has side effects.
```

**Comment by remi-delmas-3000** [comment] 2022-11-17 16:27
This is likely due to the manual removal of a number of function bodies in the proof build or to the "drop unreachable functions" part of the build.

The problem is, when a function body is missing during the DFCC pass, there is no way to know if it is intentional or not, so by default DFCC instrumentation warns about it. 

For soundness we would like to trigger an error if such a function is eventually called, but in some cases removing the body of a reachable function is a deliberate choice by the user (the user knows that it results in an underapproximation). 

I think this should be fixed upfront, i.e when dropping the function body:

1. If the function is thought to be unreachable, its body should be replaced by `assert(false); assume(false);` 
2. If the function body is thought to be reachable and removing the body is a deliberate decision, then it should have a completely empty body (i.e. not even the END_FUNCTION instruction) and we should not fail (the user knowingly removed the body) but we should still warn about it.

For case 2. we could distinguish between a function with an empty sequence of GOTO instructions and a function with a single END_FUNCTION instruction.

**Comment by remi-delmas-3000** [comment] 2022-11-17 16:56
I'll create a CBMC issue and suggest improvements to the `--drop-unused-functions` and `--remove-function-body` works.

**Comment by feliperodri** [comment] 2022-12-02 16:35
@remi-delmas-3000 have you implemented any changes to address this issue? I tested this case again with the latest CBMC version (5.71.0 (cbmc-5.59.0-879-g8ed5e40489)) and I only get the following warnings now.
```
no body for function '__CPROVER_assignable'

no body for function '__CPROVER_assignable'
```

All of the other ones starting with `DFCC instrumentation:` are gone.

**Comment by remi-delmas-3000** [comment] 2022-12-05 15:16
`assert(false)` bodies are now generated for missing functions thanks to https://github.com/diffblue/cbmc/pull/7359.

The  remaining warnings you observed
```
no body for function '__CPROVER_assignable'

no body for function '__CPROVER_assignable'
```
occur when inlining a function that contains calls  to front-end functions for specifying assigns and frees clauses `__CPROVER_assignable`, `__CPROVER_object_from`,  `__CPROVER_object_upto`, `__CPROVER_object_whole` , `__CPROVER_freeable`, etc. These warnings are normal and expected. Unfortunately we cannot silence them.

I think we can close the issue since missing bodies which are unexpected are now handled.

**Closed as completed** 2022-12-05 15:36 UTC
Labels: aws, aws-high, Code Contracts
