### ISSUE TITLE
Create iterators for `exprt` and associated utility functions

### ISSUE THREAD

**Issue by jasigal** [diffblue/cbmc#1160] opened 2017-07-20 11:45 UTC
@jasigal commented on [Thu Jul 20 2017](https://github.com/diffblue/test-gen/issues/795)

Currently there is no good, unified way to do the following:

- Determine is any subexpression satisfies a predicate
- Find a subexpression that satisfies a predicate
- Count the number of subexpressions that satisfy a predicate
- Traverse an expression to create a new data structure
- Feed all subexpressions into a function one at a time

By adding iterators to `exprt`s, we can use them to do all of the above more simply (as opposed to doing a stack based traversal by hand each time) and additionally make use of the `<algorithm>` standard library. Some functions may need to be back-ported from C++17/20.

The changes for `exprt` can be had in its class definition, and functions using these iterators specific to `exprt`s can be put in `util/expr.cpp`.

---

@peterschrammel commented on [Thu Jul 20 2017](https://github.com/diffblue/test-gen/issues/795#issuecomment-316678457)

@jasigal, move this issue to diffblue/cbmc please

**Comment by tautschnig** [comment] 2017-07-20 12:05
I agree that these are repeated problems and I'm looking forward to seeing the solution :-)

**Comment by LAJW** [comment] 2017-07-20 13:04
I'm on it.

So the first iterator would be exprt::depth_iteratort obtainable by calling exprt::depth_begin() and exprt::depth_end().

The reason for naming it depth_* instead of classic begin/end() would be to avoid confusing behaviour when calling:

````c++
for (const auto& child_expr : parent_expr)
````

 Where parent_expr is some form of an array and the expected behaviour would be to do flat traversal.

STL algorithms would still be usable, just the specific iteration choice would be made explicit. For example:

````c++
std::for_each(
    expr.breadth_begin(),
    expr.breadth_end(),
    [](const exprt&) {
    // Do stuff
});
````

**Comment by LAJW** [comment] 2017-07-21 17:03
Here's the PR.

https://github.com/diffblue/cbmc/pull/1165

**Comment by TGWDB** [comment] 2021-05-20 08:27
Closing as this is a feature request that is partially addressed and otherwise very old.

**Closed by TGWDB** 2021-05-20 08:27 UTC
