### ISSUE TITLE
Remove uses of cmdlinet::set from unit tests

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#2091] opened 2018-04-19 13:27 UTC
As discussed in #1915, using `cmdlinet::set` has no effect (unless first setting up an options map). Nevertheless there are a few uses in unit tests (some including a TODO -  @thk123).

**Comment by thk123** [comment] 2018-04-19 13:59
Note you can use (in unit tests) `free_form_cmdlinet::add_flag/set_option` which allow arbitrary flags/options to be set but then behaves like a regular `cmdlinet`

**Comment by thomasspriggs** [comment] 2022-02-03 19:21
The only uses of `cmdlinet::set` I can currently find in the unit tests are in `unit/testing-utils/free_form_cmdline.cpp`. These appear to be as intended and not surrounded by any TODO comments. Therefore this issue looks to have been addressed to me and I am going to close it out.

**Closed as completed by thomasspriggs** 2022-02-03 19:21 UTC
