### ISSUE TITLE
The function contract doesn't work when using loop

### ISSUE THREAD

**Issue by wcventure** [diffblue/cbmc#6483] opened 2021-11-28 12:23 UTC
Hi there, 

I followed the [cprover-manual/contracts-functions.md](https://github.com/diffblue/cbmc/blob/develop/doc/cprover-manual/contracts-functions.md) and tried to use function contracts in my project. However, the function contracts don't seem to work correctly in some situations. Could you help me look at the following issue?

### The `foo` function contract doesn't work when using it in the loop body

I have written a function `foo` that Iteratively checks whether the two arrays have the same elements. If yes, it returns 0, otherwise, it returns -1. And I try to use its function contract in the `main` function. Unfortunately, I got an unexpected result that all wrong assertions are Judged as SUCCESS (When this function contract is not placed in the loop, the result is correct. But when it is put into a meaningless loop, the result is not correct).

```C
//main.c
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <assert.h>

#define SIZE 10

int foo(uint32_t *map, uint32_t *key, uint32_t len)
/* Precondition */
__CPROVER_requires(len <= SIZE)
__CPROVER_requires(__CPROVER_is_fresh(map, sizeof(uint32_t)*len))
__CPROVER_requires(__CPROVER_is_fresh(key, sizeof(uint32_t)*len))
/* Postconditions */
__CPROVER_ensures(__CPROVER_return_value == 0 || __CPROVER_return_value == -1)
__CPROVER_ensures(__CPROVER_return_value == -1 ==> __CPROVER_forall {int i; (0 <= i && i < len) ==> map[i] != key[i]})
__CPROVER_ensures(__CPROVER_return_value == 0 ==> __CPROVER_exists {int i; (0 <= i && i < len) && map[i] == key[i]})
{
	int ret = -1;
	for (int i = 0; i < len; i++)
	__CPROVER_assigns(i)
	__CPROVER_loop_invariant(0 <= i && i <= len)
	__CPROVER_loop_invariant(ret == -1 || ret == 0)
	__CPROVER_loop_invariant((ret == -1)==> __CPROVER_forall {int j; (0 <= j && j < len) ==> ( j < i ==> map[j] != key[j])})
	__CPROVER_loop_invariant((ret == 0) ==> map[i] == key[i])
	__CPROVER_decreases(len - i)
	{
		if (map[i] == key[i])
		{
			ret = 0;
			break;
		}
	}
	return ret;
}

int main()
{
    uint32_t *map = malloc(sizeof(uint32_t)*SIZE);
    uint32_t *key = malloc(sizeof(uint32_t)*SIZE);
    memset(map, 0, sizeof(uint32_t)*SIZE);
    memset(key, 0, sizeof(uint32_t)*SIZE);
    key[0] = 1;
    map[0] = 2;

    int ret;
    for (int i = 1; i < SIZE; i++) {
        ret = foo(map, key, i);
    }
    assert(ret == 0);
    assert(ret == -1);
    assert(0);
}
```

You can use the following command to see the ensures clause failure.

```shell
goto-cc -o main.goto main.c
goto-instrument --replace-call-with-contract foo main.goto main-using-foo-contract.goto
cbmc main-using-foo-contract.goto
```

Then you will see all assertion success unexpectedly. The assert(0) doesn't fail which also means that the function exit is not reachable. However, if you change the loop body `for (int i = 1; i < SIZE; i++) { ret = foo(map, key, i); }` to `ret = foo(map, key, SIZE);`, the result become correct.

```shell
** Results:
[precondition.1] Check requires clause: FAILURE
/mnt/e/Github-Bitbucket/CBMC_Frama-C_By_examples/CBMCExamples/foo_and_sum_contract/loop_contract.c function main
[main.precondition_instance.1] line 41 memset destination region writeable: SUCCESS
[main.precondition_instance.2] line 42 memset destination region writeable: SUCCESS
[main.assertion.1] line 50 assertion ret == 0: SUCCESS
[main.assertion.2] line 51 assertion ret == -1: SUCCESS
[main.assertion.3] line 52 assertion 0: SUCCESS

<builtin-library-malloc> function malloc
[malloc.assertion.1] line 26 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 31 max allocation may fail: SUCCESS

** 1 of 8 failed (2 iterations)
VERIFICATION FAILED
```

**Comment by martin-cs** [comment] 2021-12-01 13:32
Thank you for the extensive examples and work-through.  This really helps.

@jimgrundy / @SaswatPadhi / @remi-delmas-3000 / @feliperodri is this something your team could look? I am pretty sure these issues would affect you too.

**Comment by jimgrundy** [comment] 2021-12-01 15:03
Yes, one of us will try to reproduce.

**Comment by tautschnig** [comment] 2021-12-01 15:17
It seems not quite all assertions succeed -- quoting from the output (which I was able to reproduce):
```
[precondition.1] Check requires clause: FAILURE
```
Given this failing precondition, no further steps will be considered. I believe the root cause of your problem is that `__CPROVER_is_fresh` will not hold once you go around the loop at least two times (it can only be fresh once).

Edit: the semantics we documented for `__CPROVER_is_fresh` state: "When using a contract as an abstraction in place of a call to the function a `__CPROVER_is_fresh` in a requires clause will check that the argument supplied is fresh," which you are not fulfilling as stated above.

**Comment by martin-cs** [comment] 2021-12-01 15:35
@jimgrundy Thank you!

**Comment by jimgrundy** [comment] 2021-12-01 17:24
Hi @wcventure, thanks for trying this out. The function and loop contracts features are very much under development, so I'm not surprised that you are finding issues, but I am grateful to hear about them and we will try to address.

Here are my thoughts so far:

Let's not use __CPROVER_is_fresh in your pre-condition for now. You shouldn't need to because you are allocating what you need via malloc in the proof harness. The idea eventually is that you won't need a proof harness at all because simply assuming that a pointer is fresh will cause it to exist. This is proving complex in general so for now my advice is to keep using a proof harness to do the memory allocation and then don't use __CPROVER_is_fresh in your contract. 

Can you try this out and report back (I'll try to find time myself later).

**Comment by wcventure** [comment] 2021-12-01 17:25
> Given this failing precondition, no further steps will be considered. I believe the root cause of your problem is that `__CPROVER_is_fresh` will not hold once you go around the loop at least two times (it can only be fresh once).

We can delete the precondition of `foo`, the `assert(0)` still could be successful.

> Let's not use __CPROVER_is_fresh in your pre-condition for now.

Hi @jimgrundy, I have tried to delete the precondition of `foo`, but the result is still not correct. However, removing the loop body in `main` and calling `foo` contract by `ret = foo(map, key, SIZE);` can get the correct result.

**Comment by tautschnig** [comment] 2021-12-01 19:47
It seems that having the three preconditions
```
__CPROVER_ensures(__CPROVER_return_value == 0 || __CPROVER_return_value == -1)
__CPROVER_ensures(__CPROVER_return_value == -1 ==> __CPROVER_forall {int i; (0 <= i && i < len) ==> map[i] != key[i]})
__CPROVER_ensures(__CPROVER_return_value == 0 ==> __CPROVER_exists {int i; (0 <= i && i < len) && map[i] == key[i]})
```
*together* is causing the trouble. Removing anyone of them will make the assertions fail as expected.

**Comment by tautschnig** [comment] 2021-12-02 15:26
I have done some further experiments, with the following now being the result of replacing the loop by:
````c
    ret = foo(map, key, 1); // 1 is important here, using a higher value like 3 will make things work
    ret = foo(map, key, 2);
````
This yields, among other things, the following goto program instructions:
```
        DECL main::1::ret : signedbv[32]
        // 15 file 6483.c line 11
        ASSERT cast(1, unsignedbv[32]) ≤ cast(10, unsignedbv[32]) // Check requires clause
        // 16 no location
        ASSUME (main::1::ret = 0 ∨ main::1::ret = -1) ∧ ((main::1::ret = -1) ⇒ ∀ ::tmp_cc::tmp_cc : signedbv[32] . (0 ≤ ::tmp_cc::tmp_cc ∧ cast(::tmp_cc::tmp_cc, unsignedbv[32]) < cast(1, unsignedbv[32])) ⇒ (*(main::1::map + cast(::tmp_cc::tmp_cc, signedbv[64])) ≠ *(main::1::key + cast(::tmp_cc::tmp_cc, signedbv[64])))) ∧ ((main::1::ret = 0) ⇒ ∃ ::tmp_cc::tmp_cc$0 : signedbv[32] . (0 ≤ ::tmp_cc::tmp_cc$0 ∧ cast(::tmp_cc::tmp_cc$0, unsignedbv[32]) < cast(1, unsignedbv[32])) ∧ *(main::1::map + cast(::tmp_cc::tmp_cc$0, signedbv[64])) = *(main::1::key + cast(::tmp_cc::tmp_cc$0, signedbv[64])))
        // 17 file 6483.c line 11
        ASSERT cast(2, unsignedbv[32]) ≤ cast(10, unsignedbv[32]) // Check requires clause
        // 18 no location
        ASSUME (main::1::ret = 0 ∨ main::1::ret = -1) ∧ ((main::1::ret = -1) ⇒ ∀ ::tmp_cc::tmp_cc$1 : signedbv[32] . (0 ≤ ::tmp_cc::tmp_cc$1 ∧ cast(::tmp_cc::tmp_cc$1, unsignedbv[32]) < cast(2, unsignedbv[32])) ⇒ (*(main::1::map + cast(::tmp_cc::tmp_cc$1, signedbv[64])) ≠ *(main::1::key + cast(::tmp_cc::tmp_cc$1, signedbv[64])))) ∧ ((main::1::ret = 0) ⇒ ∃ ::tmp_cc::tmp_cc$2 : signedbv[32] . (0 ≤ ::tmp_cc::tmp_cc$2 ∧ cast(::tmp_cc::tmp_cc$2, unsignedbv[32]) < cast(2, unsignedbv[32])) ∧ *(main::1::map + cast(::tmp_cc::tmp_cc$2, signedbv[64])) = *(main::1::key + cast(::tmp_cc::tmp_cc$2, signedbv[64])))
        // 19 file 6483.c line 61 function main
        ASSERT main::1::ret = 0 // assertion ret == 0
```
Note that `main::1::ret` is not updated between the (replaced) calls.

**Comment by jimgrundy** [comment] 2021-12-02 15:37
Thanks @wcventure for reporting this. This is a bug. We are missing a nondeterministic assignment to the return value when we replace the contract, which can result an accumulation of assumptions about the return value between two calls. We should be able to fix this soon.

**Comment by tautschnig** [comment] 2021-12-04 11:23
Thank you for reporting this problem. The issue has now been fixed via #6502.

**Comment by wcventure** [comment] 2021-12-06 11:31
Hi @tautschnig @jimgrundy, another question. Could you help me to check why the ensures clause of function `foo` fails?

I use the following command to check the function contract of `foo`.
```
goto-cc -o foo.goto main.c --function foo
goto-instrument --enforce-contract foo foo.goto foo-enforce-contracts.goto
goto-instrument --apply-loop-contracts foo-enforce-contracts.goto foo-checking-contracts.goto
cbmc foo-checking-contracts.goto --function foo
```

The CBMC reports that the postcondition could fail.
```
** Results:
[postcondition.1] Check ensures clause: FAILURE
/mnt/d/Git-bitbucket/CBMC_Frama-C_By_examples/CBMCExamples/foo_and_sum_contract/loop_contract.c function foo
[foo.1] line 17 Check that ret is assignable: SUCCESS
[foo.2] line 18 Check that i is assignable: SUCCESS
[foo.4] line 18 Check that i is assignable: SUCCESS
[foo.unwind.0] line 18 unwinding assertion loop 0: SUCCESS
[foo.3] line 28 Check that ret is assignable: SUCCESS

/mnt/d/Git-bitbucket/CBMC_Frama-C_By_examples/CBMCExamples/foo_and_sum_contract/loop_contract.c function main
[main.assertion.1] line 48 assertion ret == 0: SUCCESS

** 1 of 7 failed (2 iterations)
```

**Comment by feliperodri** [comment] 2021-12-06 18:01
Hi @wcventure, there are a few things to fix here.

First, you need to apply loop contracts before enforcement. Our contract support expect the following precedence:
  1. Loop contract instrumentation (i.e., `--apply-loop-contracts`);
  2. Function contract replacement (i.e., `--replace-call-with-contract`);
  3. Function contract enforcement (i.e., `--enforce-contract`).

You should run this example using the following steps:
```
rm *.goto
goto-cc -o foo.goto main.c --function foo
goto-instrument --apply-loop-contracts foo.goto foo-invariants.goto
goto-instrument --enforce-contract foo foo-invariants.goto foo-enforce-contracts.goto
cbmc foo-enforce-contracts.goto --function foo
```

We'll update our documentation to highlight this precedence.

Second, you need to include `ret` in your loop assigns clause.
```c
	int ret = -1;
	for (int i = 0; i < len; i++)
	__CPROVER_assigns(i, ret)
	__CPROVER_loop_invariant(0 <= i && i <= len)
	__CPROVER_loop_invariant(ret == -1 || ret == 0)
	__CPROVER_loop_invariant((ret == -1)==> __CPROVER_forall {int j; (0 <= j && j < len) ==> ( j < i ==> map[j] != key[j])})
	__CPROVER_loop_invariant((ret == 0) ==> map[i] == key[i])
	__CPROVER_decreases(len - i)
	{
		if (map[i] == key[i])
		{
			ret = 0;
			break;
		}
	}
```

Third, your loop invariant doesn't hold. You must provide an explicit upper-bound limit for all quantifiers in CBMC, if you use our SAT solver backend. Thus, you should update your invariant as follows:
```c
	__CPROVER_loop_invariant((ret == -1)==> __CPROVER_forall {int j; j <= SIZE && (0 <= j && j < len) ==> ( j < i ==> map[j] != key[j])})
```

You must do the same for ALL quantifiers (including the ones in your ensures clauses).

Last, your last ensures clause doesn't hold. @tautschnig @Herbping would that be a bug while handling exists?

Your complete example should look like this now:
```c
//main.c
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <assert.h>

#define SIZE 10

int foo(uint32_t *map, uint32_t *key, uint32_t len)
/* Precondition */
__CPROVER_requires(len <= SIZE)
__CPROVER_requires(__CPROVER_is_fresh(map, sizeof(uint32_t)*len))
__CPROVER_requires(__CPROVER_is_fresh(key, sizeof(uint32_t)*len))
/* Postconditions */
__CPROVER_ensures(__CPROVER_return_value == 0 || __CPROVER_return_value == -1)
__CPROVER_ensures(__CPROVER_return_value == -1 ==> __CPROVER_forall {int i; i <= SIZE && (0 <= i && i < len) ==> map[i] != key[i]})
__CPROVER_ensures(__CPROVER_return_value == 0 ==> __CPROVER_exists {int i; i <= SIZE && (0 <= i && i < len) && map[i] == key[i]})
{
	int ret = -1;
	for (int i = 0; i < len; i++)
	__CPROVER_assigns(i, ret)
	__CPROVER_loop_invariant(0 <= i && i <= len)
	__CPROVER_loop_invariant(ret == -1 || ret == 0)
	__CPROVER_loop_invariant((ret == -1)==> __CPROVER_forall {int j; j <= SIZE && (0 <= j && j < len) ==> ( j < i ==> map[j] != key[j])})
	__CPROVER_loop_invariant((ret == 0) ==> map[i] == key[i])
	__CPROVER_decreases(len - i)
	{
		if (map[i] == key[i])
		{
			ret = 0;
			break;
		}
	}
	return ret;
}

int main()
{
    uint32_t *map = malloc(sizeof(uint32_t)*SIZE);
    uint32_t *key = malloc(sizeof(uint32_t)*SIZE);
    memset(map, 0, sizeof(uint32_t)*SIZE);
    memset(key, 0, sizeof(uint32_t)*SIZE);
    key[0] = 1;
    map[0] = 2;

    int ret;
    for (int i = 1; i < SIZE; i++) {
        ret = foo(map, key, i);
    }
    assert(ret == 0);
    assert(ret == -1);
    assert(0);
}
```

**Comment by jimgrundy** [comment] 2021-12-06 23:47
@feliperodri asks "Last, your last ensures clause doesn't hold. @tautschnig @Herbping would that be a bug while handling exists?"

That seems like an important question to answer before we close this.  If there is a bug here can we get a new issue filed on that before closing this?

**Comment by wcventure** [comment] 2021-12-07 04:15
>__CPROVER_is_fresh will not hold once you go around the loop at least two times (it can only be fresh once).
> Let's not use __CPROVER_is_fresh in your pre-condition for now.

Hi, I found some contradictions after I did some further experiments on the complete example provided by @feliperodri.

I found that `__CPROVER_is_fresh` is necessary when proving the loop invariants and function contract for `foo` function. Because removing the precondition `__CPROVER_is_fresh` in `foo` will make the loop invariant not preserved. However, Adding `__CPROVER_is_fresh` as a precondition will make the `requires clause` doesn't hold when checking the `main` function. Because `__CPROVER_is_fresh` will not hold once you go around the loop at least two times (it can only be fresh once).

**Comment by jimgrundy** [comment] 2021-12-07 15:47
Thanks for the update @wcventure. @tautschnig is going to take a closer look at this and get back to us.

**Comment by tautschnig** [comment] 2021-12-07 23:03
Trying to answer the various questions:

1) The loop invariant needs to say
`__CPROVER_loop_invariant((ret == 0) ==> (i < len && map[i] == key[i]))` instead of `__CPROVER_loop_invariant((ret == 0) ==> map[i] == key[i])` to avoid an out-of-bounds constraint for the case of `i == len`. This makes the `ensures` clause pass.
2) To avoid the problem with `__CPROVER_is_fresh` one could use
```
__CPROVER_requires(__CPROVER_r_ok(map, sizeof(uint32_t)*len))
__CPROVER_requires(__CPROVER_r_ok(key, sizeof(uint32_t)*len))
```
but the final word on memory predicates to use might not have been spoken just yet. That is: this works here and now, but we may provide different advice in future.

**Comment by wcventure** [comment] 2021-12-08 03:32
My problem has been solved. Thank you very much!

**Closed as completed** 2021-12-08 09:04 UTC
Labels: aws-high, Code Contracts, soundness
