### ISSUE TITLE
Ubuntu 18.04 package for CBMC 5.65.0 is missing 

### ISSUE THREAD

**Issue by zhassan-aws** [diffblue/cbmc#7095] opened 2022-09-02 21:15 UTC
![image](https://user-images.githubusercontent.com/88045115/188236345-a675118a-5944-4bc1-b015-c06f2fd0d4ec.png)

Seems it failed in CI: https://github.com/diffblue/cbmc/runs/8139333515?check_suite_focus=true

**Comment by NlightNFotis** [comment] 2022-09-05 13:42
Hello, there seems to be a new version of `z3` installed in one of the actions that run per PR, but somehow we missed adding it to the release build job - which made it fail when the tests run.

I will fix it now, but we need to make a point release to fix that. We'll work on an ASAP basis to get it done today, to avoid any disruption to your release cycle.

**Comment by NlightNFotis** [comment] 2022-09-05 17:46
We have now released version [5.65.1](https://github.com/diffblue/cbmc/releases/tag/cbmc-5.65.1) which contains binaries for Ubuntu 18.04.

Apologies for any disruption caused by this.

**Comment by thomasspriggs** [comment] 2022-09-05 20:09
This issue should now be resolved by the provision of a new release. Please feel free to re-open if that does not meet your needs.

**Closed as completed by thomasspriggs** 2022-09-05 20:09 UTC
Labels: aws, aws-high

**Comment by zhassan-aws** [comment] 2022-09-06 16:05
Thanks! Would it be possible to add the 5.65.1 version to the [CBMC brew tap](https://github.com/diffblue/homebrew-cbmc)?

**Comment by NlightNFotis** [comment] 2022-09-06 16:35
@zhassan-aws I just added it to the tap.

Let us know if there are any further issues! Thanks for your patience.

**Comment by zhassan-aws** [comment] 2022-09-06 18:33
Thanks @NlightNFotis!
