### ISSUE TITLE
Error when compiling develop on MacOS

### ISSUE THREAD

**Issue by victoria-tuck** [diffblue/cbmc#7464] opened 2023-01-04 22:10 UTC
CBMC version:
commit 63703d off of develop

Operating system:
macOS Mojave 10.14.6

Exact command line resulting in the issue:
`make -C src`

What behaviour did you expect:
This to occur without error

What happened instead:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/57421145/210658126-79011eff-5e82-4453-8292-485a9bbcb606.png">

**Comment by victoria-tuck** [comment] 2023-01-04 22:33
I tried this without the -C option and it did work. I'm not sure what the difference is, but if without -C is ok then maybe this should be updated in the [compile docs](https://github.com/diffblue/cbmc/blob/develop/COMPILING.md)

**Comment by martin-cs** [comment] 2023-01-05 10:08
The `-C` is "change directory before starting".  The docs could say:

```
cd src
make
```

which is IMHO clearer, but slightly more verbose.

**Comment by tautschnig** [comment] 2023-01-12 10:38
@esteffin or @thomasspriggs Could you please take a look? I suspect that this just needs a type name for the inner element being constructed rather than leaving it to the compiler to infer it (where the compiler on 10.14 might simply be too old).

**Comment by NlightNFotis** [comment] 2023-01-16 12:14
@tautschnig Hi Michael, this came up to my attention just now.

I will have a look at this a bit later, and update you here.

**Comment by thomasspriggs** [comment] 2023-01-17 10:55
Yes, this might just need `smt_get_value_responset::valuation_pairt` adding in order to fix this. The construction should already be unambiguous as you can't construct an `std::string` using a pair of `smt_termt` as constructor parameters. I don't have a Mac on hand to test this. So I'm going to leave this with @NlightNFotis for the moment.

It is worth noting that the oldest version of MacOS we test in CI is MacOS-11. So even if we fix this particular compilation issue more are likely to crop up over time. The github actions runner for MacOS 10 is deprecated - https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

**Comment by NlightNFotis** [comment] 2023-02-08 11:10
Hello - I did have some time to look into this this morning and I have the following notes:

* First of all, I cannot reproduce it, but that's probably because I'm on a later version of the SDK and the operating system than the OP - @victoria-tuck can you please let us know what your SDK version is (`xcrun -show-sdk-version`) and what your Clang version is (`clang --version`)?
* A speculative fix (because I can't reproduce locally) would be to change the reported line from `return resultt{{valid_descriptor, valid_value}};` to `return resultt{smt_get_value_responset::valuation_pairt{valid_descriptor, valid_value}};`. This doesn't seem like a very productive change to make to me, because we depend on compiler template argument deduction on a number of places, and fixing just this one probably won't make much of a difference in the grand scheme of things - unless we have a way to find all of those places (with a compiler error perhaps?).
* I am slightly concerned with the reported issue vanishing when changing the `make` invocation. In theory the `-C` flag shouldn't change anything in the build (outside from `$PWD` while invoking `clang` et al) but could this be an issue of configuration skipped/not initialised properly outside of a specific folder?

Any thoughts here @tautschnig ?

**Comment by tautschnig** [comment] 2023-02-08 12:58
1. If @victoria-tuck can try out change proposed by @NlightNFotis and confirm this is the only change needed to get it to build then let's do it. Else what @NlightNFotis said: we can not reasonably support such compilers for we can't test.
2. The `make` "fix" might be that @victoria-tuck tried `make src`, which will just say `make: Nothing to be done for 'src'.` and happily terminate, as "src" exists (as a directory). But then `make` just didn't even try to build anything.

@victoria-tuck I think we need more information from your side at this point.

**Comment by victoria-tuck** [comment] 2023-02-23 00:21
Sdk version: 10.14.6

clang version output:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Running `make src` did just output `make: Nothing to be done for 'src'`.

The build finishes after making the change @NlightNFotis suggested above. I don't know how to test whether it worked correctly but it didn't seem to output that there were any issues.

Since this is an outdated OS issue, I think it's just past time for me to update that and then I'm assuming this wouldn't be a problem anymore.

**Comment by tautschnig** [comment] 2023-02-23 09:27
@victoria-tuck I think an easy way to test is running at least one of the regression tests, like this: `src/cbmc/cbmc regression/cbmc/Failing_Assert1/main.c`.

**Comment by victoria-tuck** [comment] 2023-02-23 22:29
Output from above

```
(base) C02YW4EXLVDQ:cbmc-git victoria_tuck$ src/cbmc/cbmc regression/cbmc/Failing_Assert1/main.c
CBMC version 5.73.0 (cbmc-5.73.0-22-g63703d27d2-dirty) 64-bit x86_64 macos
Parsing regression/cbmc/Failing_Assert1/main.c
Converting
Type-checking main
file regression/cbmc/Failing_Assert1/main.c line 7 function main: function 'assert' is not declared
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.00191155s
size of program expression: 24 steps
simple slicing removed 5 assignments
Generated 1 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 1.2309e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000139407s
Running propositional reduction
Post-processing
Runtime Post-process: 0.00013109s
Solving with MiniSAT 2.2.1 with simplifier
64 variables, 0 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000491287s
Runtime decision procedure: 0.000661616s

** Results:
regression/cbmc/Failing_Assert1/main.c function main
[main.assertion.1] line 7 assertion i == j: FAILURE

** 1 of 1 failed (2 iterations)
VERIFICATION FAILED

```

**Comment by NlightNFotis** [comment] 2023-02-24 10:14
I think we can now close the issue - it seems like you succeeded in compiling a pretty recent version of CBMC (5.73.0).

**Comment by tautschnig** [comment] 2023-02-25 18:43
> I think we can now close the issue - it seems like you succeeded in compiling a pretty recent version of CBMC (5.73.0).

But that was done using the patch you had proposed, so really we should integrate that.

**Closed as completed** 2023-03-07 15:03 UTC
Labels: Build, pending merge
