### ISSUE TITLE
Problem passing a struct member as a function parameter

### ISSUE THREAD

**Issue by thiago-cavalcante** [diffblue/cbmc#2041] opened 2018-04-11 13:42 UTC
Hi, I'm using CBMC to check my C program and I got a situation. When a pass as a function parameter a member of a struct, the verification takes way more steps than when I pass directly a parameter. for example:
```
typedef struct
{
  double mp;
  int kp;
}PKVL;

double sum(double a, double b)
{
  return a+b;
}

int main(){
  PKVL t;
  t.mp = 5.0;
  t.kp = 2;
 double x = sum(t.mp, 3.0)
 // double x = sum(2.0, 3.0)
}
```
In my real code, CBMC outputs:
- using a struct member:
```
size of program expression: 13530 steps
simple slicing removed 3062 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.0 with simplifier
743447 variables, 501498 clauses
SAT checker inconsistent: negated claim is UNSATISFIABLE, i.e., holds
Runtime decision procedure: 0.799s
VERIFICATION SUCCESSFUL
```
- using a simple parameter:
```
size of program expression: 575 steps
simple slicing removed 0 assignments
Generated 0 VCC(s), 0 remaining after simplification
VERIFICATION SUCCESSFUL
```
So, passing a struct member, I got a lot more steps, and when I pass a simple parameter, the verification is a way faster. Does CBMC work with struct?

Thanks in advance!

**Comment by tautschnig** [comment] 2018-04-11 13:52
Hello,
I'm not sure what the non-struct version of your program exactly looks like, but what you are observing is the effect of absence of constant propagation on values assigned to struct members. One remedy for that is #35, but it would be good to better understand the exact differences between the programs you are looking at to judge whether that is the full cure.

**Comment by thiago-cavalcante** [comment] 2018-04-11 14:21
Hi @tautschnig , thanks for your reply. The differences are exactly like in the example above. I don't know why this is happening.

**Comment by tautschnig** [comment] 2018-04-11 15:55
I don't quite understand: the above example doesn't given two versions of the code, so I'm not sure how I could tell the "differences"?

**Comment by thiago-cavalcante** [comment] 2018-04-11 17:36
I'm sorry. The following lines are the difference:
```
double x = sum(t.mp, 3.0)
double x = sum(2.0, 3.0)
```
In the first line is passed a member of a struct and the second line is passed a simple number. In the code given before those lines are not together.

**Comment by tautschnig** [comment] 2018-04-11 18:05
Ok, so that firmly is constant propagation: you might take a look at the differences when running cbmc with `--program-only` in  the two variants of the code. I'm not sure we have an explicit issue about this open, but the regression test `cbmc/constant_folding2` does document the problem. As said, #35 would fix it.

**Comment by tautschnig** [comment] 2018-04-11 18:06
Follow-up: if you change your code to do `PKVL t = {5.0, 2};` you should see the desired, faster behaviour as well.

**Comment by tautschnig** [comment] 2021-05-10 23:05
Closing as we by now use field sensitivity during goto-symex, which addresses exactly this issue.

**Closed as completed by tautschnig** 2021-05-10 23:05 UTC
Labels: pending merge
