### ISSUE TITLE
RAM exhaustion on reading binary GOTO

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#543] opened 2017-02-13 19:40 UTC
the attached (likely incorrect) binary GOTO of 48 bytes causes CBMC to consume > 8G of RAM on reading

[endless-loop-8G.zip](https://github.com/diffblue/cbmc/files/772197/endless-loop-8G.zip)

**Comment by TGWDB** [comment] 2021-03-24 15:23
Fix PR closed, also mentioned in other commits. Cannot reproduce now.

Closing as it is unclear that this is still a problem, please reopen if you believe this is erroneous.

**Closed by TGWDB** 2021-03-24 15:23 UTC
Labels: pending merge
