### ISSUE TITLE
Unexpected Pointer Out Of Bounds FAILURE

### ISSUE THREAD

**Issue by KVISDAOWNER** [diffblue/cbmc#5843] opened 2021-02-19 09:59 UTC
**Issue Info**
CBMC version: 5.10
Operating system: Ubuntu 20.04.1 LTS
Exact command line resulting in the issue: `cbmc stringCompare.c --function stringCompare_HARNESS --pointer-check --unwind 2 --unwinding-assertions --trace`
What behaviour did you expect: No "pointer outside object bounds" error
What happened instead: Pointer outside object bounds error

**Issue Description**
The function should be a generic string comparer that works under the assumption that the strings are properly `\0` terminated. The verification is currently set up with the assumption `__CPROVER_assume(2 == size_str)` just for simplification.

Two pointer out of bounds properties generated by the `--pointer-check` argument fail. It is caused by the dereferencing of `s1` and `s2` at line 13. I don't believe that it is possible for there to be an error, but I could be wrong. Changing `int size_str;` at line 18 to `int size_str = 2;` resolves the errors and gives the expected proof.

**Code**
```
int stringCompare(const char* s1, const char* s2) {
    if (s1 == s2)
        return 0;
    
    while (*s1 == *s2)
    {
        if (*s1 == '\0')
            return 0;
        ++s1;
        ++s2;
    }

    return *s1 - *s2; //out of bounds FAILURE (both for s1 and s2)
}


void stringCompare_HARNESS(){
    int size_str; //changing this to 'int size_str = 2;' resolves the out of bounds error

    __CPROVER_assume(2 == size_str); 

    char str1[size_str];
    char str2[size_str];

    __CPROVER_assume(str1[size_str-1] == '\0'); 
    __CPROVER_assume(str2[size_str-1] == '\0'); 

    stringCompare(str1,str2);
}

```
**Output**
```
...

Violated property:
  file github-issue.c line 13 function stringCompare
  dereference failure: pointer outside object bounds in *s1
  OBJECT_SIZE(s1) >= 1ul + (unsigned long int)POINTER_OFFSET(s1) && POINTER_OFFSET(s1) >= 0l || DYNAMIC_OBJECT(s1)


Violated property:
  file github-issue.c line 13 function stringCompare
  dereference failure: pointer outside object bounds in *s2
  OBJECT_SIZE(s2) >= 1ul + (unsigned long int)POINTER_OFFSET(s2) && POINTER_OFFSET(s2) >= 0l || DYNAMIC_OBJECT(s2)



** 2 of 29 failed (2 iterations)
VERIFICATION FAILED

```

**Comment by martin-cs** [comment] 2021-02-19 12:43
This does seem like a bug.  I know @tautschnig has just submitted a couple of PRs on pointer subtraction and bounds checking.  I don't know if those were linked with you / this report but they might be worth a try.  Are you able to try out branches?  If so

https://github.com/diffblue/cbmc/pull/5844

might be worth a try.

**Comment by KVISDAOWNER** [comment] 2021-02-19 14:16
Thank you for the fast response. I figured out how to compile the PR #5844. Now trying to run the same verification with version `CBMC version 5.24.0 (cbmc-5.24.0-1-g4a31d6265) 64-bit x86_64 linux` gives me this.

```
** 0 of 29 failed (1 iterations)
VERIFICATION SUCCESSFUL
```

So the PR version does not have the same issue :+1: (I have not tested with any other versions)

**Comment by martin-cs** [comment] 2021-02-19 14:54
OK, how about we close this issue once #5844 has been merged?  Would you like to add the test case you gave as a regression test?

**Comment by hannes-steffenhagen-diffblue** [comment] 2021-02-19 14:55
`cbmc-5.10` is quite old, I'm closing for now as it's not clear to me the bug is still present. Please try one of the more recent versions from our [releases](https://github.com/diffblue/cbmc/releases/) page (I couldn't reproduce locally with the current release version). Please let me know if you happen to run into any issues with the current release version.

**Closed as completed by hannes-steffenhagen-diffblue** 2021-02-19 14:55 UTC

**Comment by tautschnig** [comment] 2021-02-19 18:40
Just for the sake of completeness: this issue was fixed by 11431ea80bf4 (merged in #2852). I believe this is part of 5.11 (and any later version).

**Comment by KVISDAOWNER** [comment] 2021-02-19 19:27
Thanks for the response. I didn't realize the CBMC version was that old. I just downloaded what appeared to be the "newest" from cprover.org :D

**Comment by tautschnig** [comment] 2021-02-19 21:34
> Thanks for the response. I didn't realize the CBMC version was that old. I just downloaded what appeared to be the "newest" from cprover.org :D

#5260 ...
