### ISSUE TITLE
Two versions of CBMC (5.41.0 and 5.10) reports differently and older version is correct

### ISSUE THREAD

**Issue by kdw9242** [diffblue/cbmc#6413] opened 2021-10-24 07:31 UTC
CBMC version: 5.41.0 and 5.10

Operating system: Ubuntu Linux and iMac

Exact command line resulting in the issue: cbmc --unwind 100 --trace -I . ./code.c ./platform.c ./osek.c  ./trace_cbmc.c > ./cbmc_result.txt 2>&1

What behaviour did you expect: assertion property checking result of 5.41.0 and 5.10 should be same

What happened instead: 5.41.0 results wrong

I tried to check assertion property of a code using two version of CBMC 
but the results in differently even though I used the same code and command.
CBMC 5.41.0 runs on Ubuntu and CBMC 5.10 runs on iMac.
I attach the source code printed out texts.
You can see the following lines.

--- printed result by CBMC 5.41.0 ---
...
[main.assertion.1] line 296 assertion 111 && 0!=0: FAILURE
[main.assertion.2] line 297 assertion 111 && 1!=1: SUCCESS  <--- should be FAILURE
[main.assertion.3] line 298 assertion 111 && 2!=2: SUCCESS  <--- should be FAILURE
[main.assertion.4] line 299 assertion 111 && 3!=3: SUCCESS  <--- should be FAILURE
[main.assertion.5] line 300 assertion 111 && 4!=4: SUCCESS  <--- should be FAILURE
...

[reporting.zip](https://github.com/diffblue/cbmc/files/7404259/reporting.zip)

**Comment by kdw9242** [comment] 2021-10-24 07:39
I've tried it on version 5.42.0 as well, but I'm still having the problem.

**Comment by kdw9242** [comment] 2021-10-24 08:32
I found that the results are different in the two versions when the array bounds are exceeded.

**Comment by danielsn** [comment] 2021-10-28 14:11
Are you running with `--bounds-check`

**Comment by kdw9242** [comment] 2021-11-08 12:14
Sorry for the late response.
Even with the --bounds-check option, assertion checking results are still different.
Thanks for the reply.

**Comment by tautschnig** [comment] 2021-11-11 20:52
Thank you for the detailed report. I have been able to reproduce this, now also running on the same operating system. I will bisect to see what changes made parts of the code unreachable.

**Comment by tautschnig** [comment] 2021-11-16 22:45
The result of bisecting showed that  the root cause of the difference is additional constant propagation enabled by array field sensitivity (as enabled in 1f334015c24ad2af553b9dee6e127a6a24d89403). With this additional propagation you end up with the expression `{ 0, 1, 12, 19 }[4]` in multiple places (i.e., an index into an array constant), with the result of this expression being compared to different integer values. This access is out of bounds, and we generate free propositional variables for the result of this expression. There will be, however, only one set of free propositional variables, amounting to one non-deterministic value. When comparing this value to different integers, at most one such comparison can evaluate to true. Consequently, along a single path, only one of the guards can evaluate to true.

Without the constant propagation, we had different symbols that were indexed into, and the back-end would generate multiple sets of free propositional variables.

Changing `TASK_SIZE` to 5, whereupon there is no out-of-bounds access, results in the desired behaviour.

Whether multiple out-of-bounds accesses need to return consistent values is perhaps a candidate for a debate, but I don't see an immediate need for fixes. Closing the issue for now, but please feel free to reopen if you disagree.

**Closed as completed by tautschnig** 2021-11-16 22:45 UTC
Labels: soundness

**Comment by kdw9242** [comment] 2021-11-17 00:42
I also agree that it is hard to decide between non-deterministic or consistent value for the out of bounds access.

We need to apply option --bounds-check for now to avoid mis-understandings.

Thank you for checking it out, and I agree to close this issue.
Have a nice day.
