### ISSUE TITLE
CBMC dumps core "assignment to 'symbol' not handled"

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6370] opened 2021-09-29 15:33 UTC
CBMC version: 5.36.0 (cbmc-5.36.0)
Operating system: OSX
Exact command line resulting in the issue:
1. Clone this branch of RMC https://github.com/danielsn/rmc/tree/CBMC-6370
2. build rmc
3. cd src/test/rmc/CopyIntrinsics
4. rmc main.rs

What behaviour did you expect: CBMC to process the goto binary
What happened instead: 
```
CBMC version 5.36.0 (cbmc-5.36.0) 64-bit x86_64 macos
Reading GOTO program from file
Reading: main.goto
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Unwinding loop _RINvMNtCsaGHNm3cehi1_4core6optionINtB3_6OptionjE5ok_orNtNtCsixzoppbntYP_5alloc11collections19TryReserveErrorKindECs2E8QHTFQx95_4main.0 iteration 1  thread 0
assignment to 'symbol' not handled
```

**Comment by danielsn** [comment] 2021-09-29 15:33
[CopyIntrinsics.zip](https://github.com/diffblue/cbmc/files/7253198/CopyIntrinsics.zip)

**Comment by tautschnig** [comment] 2021-09-30 13:16
It seems you've got a parameter that has `code` type (i.e., is a function). Specifically, that parameter is `_RINvNtCsaGHNm3cehi1_4core3cmp6max_byjNvYjNtB2_3Ord3cmpECs2E8QHTFQx95_4main::1::var_3::compare`. CBMC doesn't currently (should it?) know how to handle functions as objects, and would instead expect a function pointer on this occasion. Is that the intended behaviour?

**Comment by tautschnig** [comment] 2022-02-14 12:51
Resolving as the issue seems to be in Kani's code, not in CBMC.

**Closed as completed by tautschnig** 2022-02-14 12:51 UTC
Labels: More info needed, aws, aws-medium
