### ISSUE TITLE
Error on recursive functions in Java

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#156] opened 2016-06-30 09:04 UTC
For recursive functions in JVM bytecode, CBMC fails with

```
main method ` ... ' has no body
```

**Comment by kroening** [comment] 2016-06-30 09:13
I have added regression/cbmc-java/recursion1 for this.

**Comment by tautschnig** [comment] 2016-07-04 08:15
I'm afraid recursion is still broken: see #163.

**Comment by mgudemann** [comment] 2016-07-11 07:56
tail recursion does work:
```
public class recursion1
{
  static int f(int n)
  {
    if(n <= 0)
      return 1;
    else
      return n * f(n-1);
  }

  static int g(int n, int acc)
  {
    if(n <= 0)
      return acc;
    else
      return g(n-1, n*acc);
  }

  public static void main(String[] args)
  {
    assert f(1)==1;
    assert g(1, 1) == 1;
  }
}
```

**Comment by smowton** [comment] 2016-08-03 17:39
Seems likely that the cause is Java locals not getting declared or added to the symtab (while temp variables *are* registered), so `goto_symext::locality` doesn't spot it as a thing to rename at inlining sites. However straightforwardly adding symbol registration and variable declaration in the same way as `new_tmp_symbol` doesn't seem to fix matters.

**Comment by smowton** [comment] 2016-08-04 09:42
Doh. `ssa_exprt.h:73` assumes that identifiers can't contain periods, but Java package names do, leading to symbol identifiers like package.function::arg0, leading to a bad l1 object identifier and use of the wrong version of a variable.

Solutions:
(1) Escape Java package identifiers (I bet there are some sites looking for last-instance-of-period to find a class name that'll need finding and fixing)
(2) Allow periods in identifier names. Likely there are more places in the codebase that don't like them?

(1) sounds like marginally less pain. Put an assert in the symtab / symbol_exprt code to check for a legal name on registration / lookup.

In the meantime flipping `#if 0` at line 67 results in correct behaviour. @kroening want to give an opinion of god on this?

Note that the fix for locality above *is* still required however, but it takes a slightly different test case to show it.

**Comment by mgudemann** [comment] 2016-08-04 09:48
Replacing `'.'` in the variable names will be necessary in java test case generation, as it is not allowed in java identfiers. Doing it already before would reduce work there, too.

**Comment by smowton** [comment] 2016-08-04 09:53
https://github.com/smowton/cbmc/commit/48118d57cd06d5d951c345bb8f7d5ddd6a8fa468: Local variable registration
https://github.com/smowton/cbmc/commit/3f8bab98f382f852bd5465f550fd069aa26dc3f5: Workaround to tolerate Java IDs
https://github.com/smowton/cbmc/commit/75e46e8bd62120d05f4f90fef1002292b3873f8a: Test case exhibiting need for local registration (otherwise `int arg_copy` gets overwritten by the recursive call)

**Comment by smowton** [comment] 2016-08-04 09:55
@mgudemann at the symtab level we'll need to use something illegal in Java IDs anyhow though, otherwise the uniqueing to avoid clashes between e.g. `java_lang_Object_equals` and a local that actually has that name will drive us insane

**Comment by smowton** [comment] 2016-08-04 13:26
Fixed in Cristina's test_gen branch

**Comment by smowton** [comment] 2016-09-07 15:31
@kroening having taken a fresh look at this today, possible options:

* Mangle Java (and other language) names to remove syntactic ambiguity for struct member vs. namespace (i.e. `s/./::/`) (substantial cleanup of every instance using `.` to find the class/namespace boundary)
* Change `ssa_exprt::build_identifier` to use a different character for the object/member boundary (less natural, risk of code assuming that `.` is used)
* Change `ssa_exprt::build_identifier` to store the L1 object identifier, or its offset, as a separate attribute of `ssa_exprt` (extra memory usage)

Any preference?

**Comment by smowton** [comment] 2016-09-16 14:16
No comment being forthcoming, how about just doing this: https://github.com/smowton/cbmc/tree/ssa_l1_id

**Closed** 2021-02-07 14:04 UTC
Labels: Java Front End, Symbolic Execution, bug
