### ISSUE TITLE
[RFC] Languages specific types are passed to `decision_proceduret::set_to` / `decision_proceduret::get`

### ISSUE THREAD

**Issue by thomasspriggs** [diffblue/cbmc#6635] opened 2022-02-03 13:07 UTC
Whilst working on the SMT support recently I noticed that expressions with the type of C language boolean `ID_c_bool` / `c_bool_typet` are passed to implementations of `decision_proceduret`. This required additions to the SMT decision procedure in order to support this language specific type. See PR  https://github.com/diffblue/cbmc/pull/6628. 

My understanding is that the ideal is for the implementation of support for language specific constructs to be limited to the the front end code; such as the code in `src/ansi_c` for the C front end. Indeed, I have not observed any similar issues for other language specific type such as `int` for example. The implementation of the `signed_int_type` in  `src/util/c_types.cpp` returns `signedbv_typet` where the original type is merely noted in `ID_C_c_type`. This enables implementations of `decision_proceduret` to support all C integer types merely by supporting `signedbv_typet` / `unsignedbv_typet`.

Are there any plans to add lowering of C boolean typed expressions into language agnostic expressions, so that `decision_proceduret` does not need to be front end language aware in this manner? Would it be a good idea to add some kind of a lowering like this if no plans for one currently exist?

**Comment by tautschnig** [comment] 2022-02-03 13:27
@thomasspriggs did enums and bitfields not give you the same grief? I'm with you that we shouldn't have to handle types like `c_bool_typet` in the back-end, but I thought the same applied to `c_enum_typet` and `c_bitfield_typet`.

One option that I at least thought about (and I'd be very keen to receive @kroening's input here) is to turn all these into annotations onto their underlying type. That is, have any symbols that use those types just get signed/unsigned bitvector types with an irep comment indicating that they are `c_bool`, `c_enum`, `c_bitfield`.

**Comment by thomasspriggs** [comment] 2022-02-03 15:45
@tautschnig We have not tested with enums or bit fields yet. We fixed the issue within the SMT support for `c_bool_typet` and raised this issue about it as it was the first instance of this which we have discovered and it seems like a potential architectural issue. However we absolutely should test to see if this particular issue applies to these other types as well.

**Comment by kroening** [comment] 2022-02-03 15:49
The decision procedure is the right place to do the lowering, since
a) the decision procedure knows best what needs to be lowered;
b) there may be a choice of lowerings, and some lowerings might work for some decision procedures but not for others;
c) the data types supported by external decision procedures will change over time, and we'd basically 'outsource' our IR semantics to somebody else.

To deal with configurable, language-dependent sorts in the decision procedure we can use the idea of underlying types, as hinted at by @tautschnig.

**Comment by tautschnig** [comment] 2022-05-11 11:25
Closing as the current status is as intended.

**Closed as completed by tautschnig** 2022-05-11 11:25 UTC
Labels: SMT Backend Interface, C Front End, RFC
